source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
  pod 'GAppAuth', path: '../'
end

target 'GAppAuth-iOS' do
  platform :ios, '9.0'
  shared_pods
end

target 'GAppAuth-macOS' do
  platform :osx, '10.11'
  shared_pods
end
